exports_files(glob(["**/*.hpp"]))  # Export all .hpp files recursively

cc_library(
    name = "order_type",
    hdrs = ["order_type.hpp"],  # Specify the header file
    visibility = ["//visibility:public"],  # Make it available to other Bazel targets
)
