cc_test(
    name = "test_order_node",
    srcs = ["exchange/test_order_node.cpp"],
    copts = ["-Iinclude"],
    deps = [
        "//src/exchange:order_node",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
